chainweb:
  #  allowReadsInLocal: false
  #  backup:
  #    api:
  #      configuration: {}
  #      enabled: false
  #    directory: null
  #  chainwebVersion: mainnet01
  #  cuts:
  #    fastForwardBlockHeightLimit: null
  #    fetchTimeout: 3000000
  #    initialBlockHeightLimit: null
  #    pruneChainDatabase: none
  #  gasLimitOfBlock: 150000
  #  headerStream: false
  #  localRewindDepthLimit: 1000
  #  logGas: false
  #  mempoolP2p:
  #    configuration:
  #      maxSessionCount: 6
  #      pollInterval: 30
  #      sessionTimeout: 300
  #    enabled: true
  #  minGasPrice: 1.0e-8
  #  mining:
  #    coordination:
  #      enabled: false
  #      limit: 1200
  #      miners: []
  #      updateStreamLimit: 2000
  #      updateStreamTimeout: 240
  #    nodeMining:
  #      enabled: false
  #      miner:
  #        account: ''
  #        predicate: keys-all
  #        public-keys: []
  #  moduleCacheLimit: 62914560
  #  onlySyncPact: false
  #  p2p:
  #    bootstrapReachability: 0.5
  #    ignoreBootstrapNodes: false
  #    maxPeerCount: 50
  #    maxSessionCount: 10
  #    peer:
  #      certificateChain: null
  #      certificateChainFile: null
  #      hostaddress:
  #        hostname: 0.0.0.0
  #        port: 1789
  #      interface: '*'
  #      key: null
  #      keyFile: null
  #    peers: []
  #    private: false
  #    sessionTimeout: 240
  #  pactQueueSize: 2000
  #  preInsertCheckTimeout: 1000000
  #  reintroTxs: true
  #  reorgLimit: 480
  #  rosetta: false
  #  serviceApi:
  #    interface: '*'
  #    payloadBatchLimit: 1000
  #    port: 1848
  #    validateSpec: false
  #  syncPactChains: null
  throttling:
    global: 50.0
    mempool: 20.0
    putPeer: 11
      #databaseDirectory: null
      #logging:
      #  backend:
      #    color: auto
      #    format: text
      #    handle: stdout
      #  clusterId: null
      #  filter:
      #    default: debug
      #    default-rate: 1
      #    rules: []
      #  logger:
      #    exception_limit: 10
      #    exception_wait: 1000
      #    exit_timeout: 1000000
      #    log_level: info
      #    policy: discard
      #    queue_size: 1000
      #    scope: []
      #  telemetryBackend:
      #    configuration:
      #      color: auto
      #      format: text
      #      handle: stdout
      #    enabled: true
      #resetChainDatabases: false
